Adjustment/history font size
maxellmilay/tmi pull request #33
Opened 2023-02-03 12:05 UTC by Wetooa

**changes**

- increased font-size sa history (pa check ko if good enough raba, gi mata mata ra nako baya sa figma
- fixed little issue sa statement

2023-02-03 12:15 UTC, ezerssss requested changes

2023-02-03 12:15 UTC, ezerssss commented on components/about/History.tsx
> +          <h1 className="text-white text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold ml-5 sm:ml-9 md:ml-14">
![image](https://user-images.githubusercontent.com/72904036/216600496-337ff0ca-0391-4e32-bff7-244bdf7689d9.png)

ma fuck up siya sa smallest size (320px)

2023-02-03 12:15 UTC, ezerssss commented on components/about/StatementDetail.tsx
> +      <p className="absolute -z-10 shadow-blue text-7xl sm:text-9xl opacity-70 font-garamond text-outlined text-white number-container">
![Uploading image.png…]()

dili lagi centered ang number

2023-02-03 15:44 UTC, Wetooa commented on components/about/History.tsx
> +          <h1 className="text-white text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold ml-5 sm:ml-9 md:ml-14">
oof mb ako na miss. ako lang i change back sa original

2023-02-04 05:14 UTC, ezerssss approved these changes

2023-02-04 05:15 UTC, merged